apiVersion: v1
kind: Service # serivcio para exponer las metricas del mi aplicacion
metadata:
  name: runners-app-metrics
  labels:
    app: runners-app
spec:
  selector:
    app: runners-app
  ports:
    - name: metrics
      port: 9000
      targetPort: 9000
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: prometheus
  namespace: monitoring
spec:
  virtualhost:
    fqdn: prometheus.gz.com
  routes:
    - conditions:
        - prefix: /
      services:
        - name: kube-prom-stack-kube-prome-prometheus
          port: 9090
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: alertas
  namespace: monitoring
spec:
  virtualhost:
    fqdn: alertas.gz.com
  routes:
    - conditions:
        - prefix: /
      services:
        - name: kube-prom-stack-kube-prome-alertmanager
          port: 9093
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: grafana
  namespace: monitoring
spec:
  virtualhost:
    fqdn: grafana.gz.com
  routes:
    - conditions:
        - prefix: /
      services:
        - name: kube-prom-stack-grafana
          port: 80              