apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: message-queue
    component: consumer
    chapter: cron-jobs
  name: consume-cron
spec:
  schedule: "* * * * *" # ejecuta el Job cada minuto.
  jobTemplate:
    spec:
      parallelism: 2 # número de pods que se ejecutarán en paralelo cada vez que se ejecute el Job
      template: # Plantilla con la definición del Pod que va a crear el Job
        metadata:
          labels:
            app: message-queue
            component: consumer
            chapter: jobs
        spec:
          containers:
          - name: worker
            image: "docker.io/egsmartin/kuard:latest"
            imagePullPolicy: Always
            command:
            - "/kuard"
            args:
            - "--keygen-enable"
            - "--keygen-exit-on-complete"
            - "--keygen-memq-server=http://queue:8080/memq/server"
            - "--keygen-memq-queue=keygen"
          restartPolicy: OnFailure # encaso de fallo, no se reintenta el Pod, así que el Job tratará de crear un nuevo Pod
