apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: message-queue
    component: consumer
    chapter: jobs
  name: consumers
spec:
  parallelism: 5 # número de pods que se ejecutarán en paralelo. No se especifica completions, así que el Job se considerará completado cuando terminen los 5 pods, esto es, no se crearán pods adicionales
  template:
    metadata:
      labels:
        app: message-queue
        component: consumer
        chapter: jobs
    spec:
      containers:
      - name: worker
        image: "docker.io/egsmartin/kuard:latest"
        imagePullPolicy: Always
        command:
        - "/kuard"
        args:
        - "--keygen-enable"
        - "--keygen-exit-on-complete"
        - "--keygen-memq-server=http://queue:8080/memq/server"
        - "--keygen-memq-queue=keygen"
      restartPolicy: OnFailure # encaso de fallo, no se reintenta el Pod, así que el Job tratará de crear un nuevo Pod
