apiVersion: v1
kind: Pod
metadata:
  name: amicontained
#  annotations:
#    container.apparmor.security.beta.kubernetes.io/amicontained: "runtime/default" # Habilitar AppArmor con el contenedor aimcontained y le asocia el perfil runtime/default. AppArmor debe estar habilitado en el nodo. Este perfil es el que viene por defecto en la mayoría de las distribuciones Linux. El perfil determina que acciones puede realizar el contenedor, que archivos puede leer, que capacidades del kernel puede usar, etc.
spec:
  securityContext:
    runAsNonRoot: true # no permitir que el contenedor se ejecute como root
    runAsUser: 1000 #user ID con el que se ejecutara el pod
    runAsGroup: 3000 #group ID con el que se ejecutara el pod. Tiene que existir en la imagen del contenedor y ser un grupo del usuario con el que se ejecuta el contenedor
    fsGroup: 2000 #los archivos que se creen en los volúmenes montados serán propiedad de este grupo
    seccompProfile:
      type: RuntimeDefault
  containers:
    - image: jess/amicontained:v0.4.9
      name: amicontained
      command: [ "/bin/sh", "-c", "--" ]
      args: [ "amicontained" ]
      securityContext:
        capabilities: #añadimos y quitamos capacidades del kernel al contenedor
            add: ["SYS_TIME"]
            drop: ["NET_BIND_SERVICE"]
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true #el filesytem montado como root del contenedor sera de solo lectura
        privileged: false # no ejecutamos en modo privilegiado, aunque si activamos algunas capabilities del kernel
