apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: <NAME>
spec:
  request: <CSR_BASE64>
  signerName: kubernetes.io/kube-apiserver-client
  usages:
    - client auth
