apiVersion: apps/v1
kind: Deployment
metadata:
  name: primos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primos
  template:
    metadata:
      labels:
        app: primos
    spec:
      containers:
      - name: primos
        image: docker.io/egsmartin/primos:latest
        ports:
        - containerPort: 8080 # puerto del contenedor
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080 # puerto para la probe. Pasados 30 segundos tenemos 10 para contestar. Sino contestamos no se serviran peticiones
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080 # puerto para la probe. Si no se supera se destruirá y creará otro pod
          initialDelaySeconds: 5 # esperamos 5 segundos para lanzar la probe
          periodSeconds: 5 # y cada 5 segundos la comprobamos
---
apiVersion: v1
kind: Service
metadata:
  name: primos
spec:
  selector:
    app: primos
  ports:
  - port: 80 # puerto del servicio
    targetPort: 8080 # puerto del contenedor
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: primos-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment # Vamos a escalar un deployment (podria haber sido una replicaset)
    name: primos-deployment
  minReplicas: 1 # número mínimo de réplicas
  maxReplicas: 10 # número máximo de réplicas
  metrics:
  - type: Resource
    resource:
      name: cpu #vigilamos la cpu
      target:
        type: Utilization
        averageUtilization: 50 # no puede superar el 50% de uso de cpu
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10  # Ventana de estabilización (5 minutos)
      policies:
      - type: Percent
        value: 50  # Reduce hasta un 50% de las réplicas actuales por minuto
        periodSeconds: 60
      - type: Pods
        value: 1  # O reduce 1 réplica por minuto, lo que sea mayor
        periodSeconds: 60
      selectPolicy: Max  # Usa la política que reduzca más
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-ingress
spec:
  ingressClassName: contour
  rules:
    - host: gz.com
      http:
        paths:
          - path: /primos
            pathType: Prefix
            backend:
              service:
                name: primos
                port:
                  number: 80 # puerto donde se expone el servicio
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: balanceo
  namespace: default
spec:
  virtualhost:
    fqdn: multiplica.gz.com
  routes:
    - conditions:
      - prefix: /
      services:
        - name: mult3
          port: 80
          weight: 30
        - name: mult2
          port: 80
          weight: 70
      loadBalancerPolicy:
        strategy: RoundRobin # Estrategia de balanceo de carga. Sino se informa se aplica RoundRobin. Otras opciones son Random y WeightedLeastRequest. Podemos habilitar afinidad de sesion informando como strategy Cookie.
