apiVersion: v1
kind: Service
metadata:
  name: primos-service
spec:
  selector:
    app: primos
  ports:
  - port: 80 # puerto del servicio
    targetPort: 8080 # puerto del contenedor
  type: LoadBalancer # declaramos el servicio como LoadBalancer, esto creara una external ip