tempo:
  reportingEnabled: false
  retention: 24h
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  metricsGenerator:
    enabled: true
    remoteWriteUrl: http://kps-kube-prometheus-stack-prometheus.observability.svc:9090/api/v1/write

serviceMonitor:
  enabled: true

persistence:
  enabled: true
  size: 10Gi

