apiVersion: apps/v1
kind: Deployment # creamos un deployment para desplegar nuestro operador
metadata:
  name: multiplicador-operator
  namespace: default
  labels:
    app: multiplicador-operator # selector que identifica los pods del deployment
spec:
  replicas: 1 # una replica
  selector:
    matchLabels:
      app: multiplicador-operator
  template:
    metadata:
      labels:
        app: multiplicador-operator
    spec:
      serviceAccountName: multiplicador-operator # el contenedor del operador se ejecuta con la cuenta de servicio que hemos definido antes, que tiene los permisos necesarios para trabajar con los recursos que el operador necesita gestionar
      containers:
        - name: operator
          image: multiplicador-operator:debug # la imagen del operador que hemos construido y cargado en el cluster con kind load docker-image
          imagePullPolicy: Always
          args: []
          ports:
            - containerPort: 40000
              protocol: TCP
          resources: # recuros asignados y máximos que podrá usar el operador
            limits:
              cpu: "100m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "128Mi"
