USER-SUPPLIED VALUES:
admintools:
  enabled: true
  image:
    repository: temporalio/admin-tools
    tag: latest
server:
  additionalEnv:
    - name: AWS_ACCESS_KEY_ID
      value: "minio"
    - name: AWS_SECRET_ACCESS_KEY
      value: "minio123"
    - name: AWS_REGION
      value: "us-east-1"
    - name: AWS_EC2_METADATA_DISABLED
      value: "true"
  config:
    namespaces:
      default:
        retention: 86400
    persistence:
      datastores:
        default:
          sql:
            connectAddr: mi-postgres-rw.database.svc.cluster.local:5432
            connectProtocol: tcp
            createDatabase: true
            databaseName: temporal
            driverName: postgres12
            existingSecret: mi-temporal-secret
            manageSchema: true
            pluginName: postgres12
            secretKey: password
            user: egsmartin
        visibility:
          sql:
            connectAddr: mi-postgres-rw.database.svc.cluster.local:5432
            connectProtocol: tcp
            createDatabase: true
            databaseName: temporal_visibility
            driverName: postgres12
            existingSecret: mi-temporal-secret
            manageSchema: true
            pluginName: postgres12
            secretKey: password
            user: egsmartin
  frontend:
    replicaCount: 1
  history:
    replicaCount: 1
  matching:
    replicaCount: 1
  replicaCount: 1
  worker:
    replicaCount: 1
  archival:
    history:
      state: "enabled"
      enableRead: true
      provider:
        s3store:
          endpoint: "http://minio.minio.svc.cluster.local:9000"
          region: "us-east-1"
          s3ForcePathStyle: true

    visibility:
      state: "enabled"
      enableRead: true
      provider:
        s3store:
          endpoint: "http://minio.minio.svc.cluster.local:9000"
          region: "us-east-1"
          s3ForcePathStyle: true
  namespaceDefaults:
    archival:
      history:
        state: "enabled"
        URI: "s3://temporal-history"
      visibility:
        state: "enabled"
        URI: "s3://temporal-visibility"
web:
  replicaCount: 1
