apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mi-postgres
  namespace: database
spec:
  instances: 2
  # Optionally specify a container image (e.g. "postgres:16")
  # imageName: postgres:16
  storage:
    size: 2Gi
    storageClass: local-path
  bootstrap:
    initdb:
      database: mi-db
      owner: egsmartin
      secret:
        name: mi-db-secret

