apiVersion: v1
kind: Namespace
metadata:
  name: database
---
apiVersion: v1
kind: Secret
metadata:
  name: mi-db-secret
  namespace: database
type: Opaque
stringData:
  username: "egsmartin"
  password: "prueba"
  postgresql-password: "prueba"
